---
title: "Keto-AD_notebook"
author: "GMB"
date: "03/11/2020"
output: html_document
---
Open R and load libraries
```{r setup, eval=FALSE, include=FALSE}
library(TCC)
library(dplyr)
library(pheatmap)
library(hablar)
library(forcats)
library(pheatmap)
library(ggrepel)
library(dendsort)
library(pheatmap)
library(extrafont)
library(biomaRt)
library(VennDiagram)
library(data.table)
```

import raw counts
```{r}
RAWcounts <- read.table("summary_star_genes_readcount.stranded.annotated.tsv", stringsAsFactors = FALSE, header = T, row.names = 1)

#keep only protein coding entries
RAWcounts_genes <- RAWcounts[RAWcounts$Category %like% "protein_coding",] #%like% from data.table package
RAWcounts_genes <- RAWcounts_genes[-c(1:4),]

#clean up the output, 
rownames(RAWcounts_genes) <- make.unique(RAWcounts_genes[,"Name"], sep = ".") #set row names
RAWcounts_genes <- RAWcounts_genes[,1:24] #keep only data columns

```

2020-11-03: generate normalized table of all protein_coding transcripts
```{r}
group <- c(1,1,1,2,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6)
full <- count ~ condition
reduced <- count ~ 1
tcc_transcripts <- new("TCC", RAWcounts_genes, group)
tcc_transcripts <- calcNormFactors(tcc_transcripts, norm.method = "tmm", test.method = "edger", iteration = 3, full = full, reduced = reduced)

normCounts_transcripts <- as.data.frame(getNormalizedData(tcc_transcripts))

write.csv(normCounts_transcripts, file = "normalized_genes.csv")
```


Identify DEGs between all samples and generate crude heatmap
```{r}

#get DEG
tcc_transcripts <- estimateDE(tcc_transcripts, test.method = "deseq2", FDR = 0.1)
result <- getResult(tcc_transcripts, sort = F)
table(tcc_transcripts$estimatedDEG) #644 DEG or 1042 (@ pVal < 0.01)
plot(tcc_transcripts)

#generate mean values table
normCounts_mean <- as.data.frame(cbind(rowMeans(normCounts_transcripts[,1:3]), rowMeans(normCounts_transcripts[,4:8]), rowMeans(normCounts_transcripts[,9:12]), rowMeans(normCounts_transcripts[,13:16]), rowMeans(normCounts_transcripts[,17:20]), rowMeans(normCounts_transcripts[,21:24])))
colnames(normCounts_mean) <- c("3xTg_C", "3xTg_K", "3xTg_M", "WT_C", "WT_K", "WT_M")

#keep only DEG
normCounts_mean_DEG_FDR01 <- normCounts_mean[result$estimatedDEG == 1,]
normCounts_mean_DEG_001 <- normCounts_mean[result$p.value < 0.01,]
normCounts_DEG_001 <- normCounts_transcripts[result$p.value < 0.01,]

#generate heatmap
hm_mean_DEG <- pheatmap(normCounts_mean_DEG_001, scale = "row", clustering_distance_rows = "correlation", show_rownames = F, treeheight_col = 10, cellwidth = 40)
hm_DEG <- pheatmap(normCounts_DEG_001, scale = "row", clustering_distance_rows = "correlation", show_rownames = F, treeheight_col = 10, cellwidth = 10)
```


generate pair analysis objects
```{r}
WTvs3xTg_C_counts <- RAWcounts_genes[,c(13:16, 1:3)]
WT_CvsM_counts <- RAWcounts_genes[,c(13:16,21:24)]
Tg_CvsM_counts <- RAWcounts_genes[,c(1:3,9:12)]
WT_CvsK_counts <- RAWcounts_genes[,c(13:16, 17:20)]
Tg_CvsK_counts <- RAWcounts_genes[,c(1:8)]
WT_Cvs_3xTg_M_counts <- RAWcounts_genes[,c(13:16, 9:12)]
WT_Cvs_3xTg_K_counts <- RAWcounts_genes[,c(13:16, 4:8)]

group_pairs43 <- c(1,1,1,1,2,2,2)
group_pairs44 <- c(1,1,1,1,2,2,2,2)
group_pairs34 <- c(1,1,1,2,2,2,2)
group_pairs35 <- c(1,1,1,2,2,2,2,2)
group_pairs45 <- c(1,1,1,1,2,2,2,2,2)

#create TCC objects
WTvs3xTg_C <- new("TCC", WTvs3xTg_C_counts, group = group_pairs43)
WT_CvsM <- new("TCC", WT_CvsM_counts, group = group_pairs44)
Tg_CvsM <- new("TCC", Tg_CvsM_counts, group = group_pairs34)
WT_CvsK <- new("TCC", WT_CvsK_counts, group = group_pairs44)
Tg_CvsK <- new("TCC", Tg_CvsK_counts, group = group_pairs35)
WT_Cvs_3xTg_M <- new("TCC", WT_Cvs_3xTg_M_counts, group = group_pairs44)
WT_Cvs_3xTg_K <- new("TCC", WT_Cvs_3xTg_K_counts, group = group_pairs45)

WTvs3xTg_C <- degAnalysis(WTvs3xTg_C)
WTvs3xTg_C_analysis <- degAnalysisFile(WTvs3xTg_C)
WTvs3xTg_C_analysis %>% mutate("DEG_pval001" = WTvs3xTg_C_analysis$p.value < 0.01) -> WTvs3xTg_C_analysis
write.csv(WTvs3xTg_C_analysis, file = "WTvs3xTg_C.csv")

WT_CvsM <- degAnalysis(WT_CvsM)
WT_CvsM_analysis <- degAnalysisFile(WT_CvsM)
WT_CvsM_analysis %>% mutate("DEG_pval001" = WT_CvsM_analysis$p.value < 0.01) -> WT_CvsM_analysis
write.csv(WT_CvsM_analysis, file = "WT_CvsM.csv")

WT_CvsK <- degAnalysis(WT_CvsK)
WT_CvsK_analysis <- degAnalysisFile(WT_CvsK)
WT_CvsK_analysis %>% mutate("DEG_pval001" = WT_CvsK_analysis$p.value < 0.01) -> WT_CvsK_analysis
write.csv(WT_CvsK_analysis, file = "WT_CvsK.csv")

Tg_CvsM <- degAnalysis(Tg_CvsM)
Tg_CvsM_analysis <- degAnalysisFile(Tg_CvsM)
Tg_CvsM_analysis %>% mutate("DEG_pval001" = Tg_CvsM_analysis$p.value < 0.01) -> Tg_CvsM_analysis
write.csv(Tg_CvsM_analysis, file = "Tg_CvsM.csv")

Tg_CvsK <- degAnalysis(Tg_CvsK)
Tg_CvsK_analysis <- degAnalysisFile(Tg_CvsK)
Tg_CvsK_analysis %>% mutate("DEG_pval001" = Tg_CvsK_analysis$p.value < 0.01) -> Tg_CvsK_analysis
write.csv(Tg_CvsK_analysis, file = "Tg_CvsK.csv")

WT_Cvs_3xTg_M <- degAnalysis(WT_Cvs_3xTg_M)
WT_Cvs_3xTg_M_analysis <- degAnalysisFile(WT_Cvs_3xTg_M)
WT_Cvs_3xTg_M_analysis %>% mutate("DEG_pval001" = WT_Cvs_3xTg_M_analysis$p.value < 0.01) -> WT_Cvs_3xTg_M_analysis
write.csv(WT_Cvs_3xTg_M_analysis, file = "WT_Cvs_3xTg_M.csv")

WT_Cvs_3xTg_K <- degAnalysis(WT_Cvs_3xTg_K)
WT_Cvs_3xTg_K_analysis <- degAnalysisFile(WT_Cvs_3xTg_K)
WT_Cvs_3xTg_K_analysis %>% mutate("DEG_pval001" = WT_Cvs_3xTg_K_analysis$p.value < 0.01) -> WT_Cvs_3xTg_K_analysis
write.csv(WT_Cvs_3xTg_K_analysis, file = "WT_Cvs_3xTg_K.csv")

comparison_list <- "WT_Cvs_3xTg_K_analysis"
  #c("WTvs3xTg_C_analysis", "WT_CvsK_analysis", "WT_CvsM_analysis", "Tg_CvsM_analysis", "Tg_CvsK_analysis", "WT_Cvs_3xTg_M_analysis" )

#pathway analysis on all DEGs
for (i in comparison_list){
  j <- get(i) #Add option to analyze all genes or split Up and downreg
  gpro_test <- gost(j[j$DEG_pval001 == T, 1], organism = "mmusculus", sources = "GO:BP", evcodes = T)
  df <- as.data.frame(apply(gpro_test$result, 2, as.character))
  write.csv(df, file = paste(i,"_pathways.csv", sep = ""))
}

#separate pathway analysis on up and down DEGs
for (i in comparison_list){
  j <- get(i) 
  #upreg DEG
  gpro_test <- gost(j[j$DEG_pval001 == T & j$rank > 0, 1], organism = "mmusculus", sources = "GO:BP", evcodes = T)
  if (!is.null(gpro_test)){
    df <- as.data.frame(apply(gpro_test$result, 2, as.character))
    write.csv(df, file = paste(i,"_upreg_pathways.csv", sep = ""))
  }
  
  #downreg DEG
  gpro_test <- gost(j[j$DEG_pval001 == T & j$rank < 0, 1], organism = "mmusculus", sources = "GO:BP", evcodes = T)
  if (!is.null(gpro_test)){
    df <- as.data.frame(apply(gpro_test$result, 2, as.character))
    write.csv(df, file = paste(i,"_downreg_pathways.csv", sep = ""))
  }
}
```

Output normalized and s-score scaled data
```{r}
write.csv(normCounts_transcripts, file = "./NormCounts.csv")
zscore_normCounts <- t(scale(t(normCounts_transcripts)))[,c(13:24, 1:12)]
write.csv(zscore_normCounts, file = "./NormCounts_zscore.csv")
```

generate heatmap of DEG lists
```{r}
metab <- c("Gdap1", "Acsl3", "Mff", "Ssb", "Scg5", "Mal", "Ift52", "Glrb", "Ncbp1", "Eps15", "Stx12", "Cdc42", "Scarb2", "Vps29", "Cct6a", "Ift22", "Copg2", "Ptn", "Vhl", "Golga7", "Vps35", "Thy1", "Tmem30a", "Lztfl1", "Skp1a", "Snap47", "Arl4d", "Atp6v1d", "Hsp90aa1", "Vps41", "Thoc7", "Spcs1", "Kpna3", "Ift27", "Riok2", "Rab31", "Snx2", "Atad1", "06-Sep", "Bcap31", "Tmsb4x", "Cnp", "Slc25a5", "Ppid", "Chmp5", "Cyp51", "Vps50", "Arl6ip5", "Timm8b", "Cck", "Azin1", "Slc35a5", "Ndufb3", "Crot", "Pink1", "Slc25a13", "Ndufc2", "Sdhd", "Dnajc15", "Slc1a3", "Ndufs8", "Mt-nd2", "Mt-co1", "Mt-nd4", "Mt-cytb", "Glrx", "Sucla2", "Mt-nd1", "Atp5c1", "Atp5j2", "App", "Ppp1r3c", "Mt-nd4", "Mt-nd2", "Mt-nd1", "Hmgcs2", "Mt-cytb", "Mt-co1", "Fdft1", "Sc5d", "Hmgcs1", "Hmgcs2")
synapse <- c("Tagap", "Rapgefl1", "Neurl1b", "Igf1r", "Ppp1r12b", "Jph4", "Slc16a2", "Rimbp2", "Sipa1l2", "Gng7", "Sv2c", "Neto1", "Cacna1h", "Dlgap4", "Ksr2", "Gm45844", "Scube3", "Traf3", "Irs1", "Cacna1d", "Sorcs2", "Safb", "Ube2o", "Wdfy1", "Jph3", "Lgr6", "Slc25a5", "Ddit4l", "Pak1ip1", "Arhgef3", "Bcap31", "Lurap1l", "Snap47", "Sgk3", "Ccny", "Scg5", "Rnf34", "Tlr7", "Atad1", "Glrx", "Ndufc2", "Fabp5", "Arl6ip5", "Serinc3", "Npsr1", "Chmp5", "Rasl11b", "Vip", "Eps15", "Grm3", "Nts")
Neural <- c("Raph1", "Nrp2", "Kif1a", "Atp2b4", "Nav1", "Cfh", "Ush2a", "Prox1", "Nsmf", "Notch1", "Ntng2", "Lamc3", "Nr4a2", "Map1a", "Snph", "Sox12", "Src", "Sox2", "Fat4", "Slc7a11", "Mef2d", "Efna1", "Notch2", "Csf1", "Celsr2", "Col25a1", "Chd7", "Nr4a3", "Jun", "Ror1", "Adgrb2", "Arid1a", "Spen", "Chd5", "Fryl", "Kit", "Hnrnpd", "Adam1a", "Fry", "Smo", "Plxna4", "Setd5", "Ift122", "Lrtm2", "Mboat7", "Mark4", "Cic", "Lgi4", "Shank1", "Nav2", "Inppl1", "Stx1b", "Shank2", "Efnb2", "Prag1", "Adgrl1", "Nfix", "Hydin", "Cdon", "Sorl1", "Zfp609", "Bsn", "Ank3", "Palm", "Lrp1", "Adcy1", "Rnf112", "Nlgn2", "Rap1gap2", "Serpinf1", "Git1", "Sox9", "Foxj1", "Rbfox3", "Mycn", "Sox11", "Syne2", "Zfp36l1", "Irf2bpl", "Clmn", "Bcl11b", "Foxc1", "Map1b", "Zmiz1", "Zfhx2", "Adgrb1", "Shank3", "Hdac7", "Adamts1", "Syngap1", "Bag6", "Zfp521", "Camk2a", "Mark2", "Kcnip2", "Neurl1a", "Xlr4b", "Fzd7", "Igfbp5", "Prrc2c", "Kif26b", "Foxo1", "Frem2", "Adar", "Col11a1", "Ankrd6", "Hivep3", "Ptpru", "Kdr", "Mmp17", "Gtf2i", "Flt1", "Hmgb1", "Cacna1c", "Plekha5", "Oscar", "Epn1", "Insr", "Junb", "Cbfa2t3", "Ankrd11", "Bcl9l", "Nphp3", "Clec3b", "Sobp", "Arid5b", "Ptprb", "Agap2", "Wfikkn2", "Axin2", "Actn1", "Ston2", "Foxq1", "Flnb", "Il17rd", "Sox21", "Card10", "Ano6", "Nr4a1", "Myh11", "Cblb", "Col8a1", "Igf2r", "Smoc2", "Tshz1", "Polr1b", "Wdfy3", "Tet3", "Ddx4", "Kmt2d", "Brd4", "H2-Q7", "Arap1", "Cdc42ep4", "Myo10", "Xlr4a", "Huwe1", "Prrc2b", "Gnb3", "Polg", "Fam57b", "Wwc1", "Tob1", "Sema5a", "Prrc2a", "Trim8", "Cfap46", "Mtss2", "Ajm1", "Olfml2a", "Epb41l1", "Kcnb1", "Kcng1", "Slc16a1", "Tifa", "Dlgap3", "Pitpnm2", "Pom121", "Trrap", "Nup210", "Iqsec3", "Chd4", "Shisa7", "Slc8a2", "Adamts17", "Fus", "Znrf1", "Apc2", "Celf5", "Ikzf4", "Chd3", "Doc2b", "Mllt6", "Dync1h1", "Phf2", "Mast4", "Kat6b", "Nisch", "Plec", "Cbx6", "Cacnb3", "Crebbp", "Rtp1", "Ttbk1", "Riok3", "Syt7", "Cldn2", "Vps35", "Stmn2", "Cdkl5", "Plp1", "Thy1", "Nrep", "App", "Tmem30a", "Cck", "Vwc2l", "Chn1", "Gfap", "Plk2", "Serpine2", "Serpini1", "Neurog2", "Scarb2", "Ptn", "Vhl", "Bend6", "Cntn4", "Tspan2", "Mtmr2", "Slc1a3", "Cdc42", "Cnp", "Ift27", "Hsp90aa1", "Slc11a2", "2610301b20rik", "Ntm", "Cst3", "Rnf2", "Mlh1", "Gpx1", "Pafah1b2", "Hnmt", "Mbp", "Meis2", "Lgals8", "Atraid", "Ccr1", "Ddah1", "Sdcbp", "Acsl3", "C1qc", "Neurod6", "S100a1", "Chil1", "Mt-co1", "Mt-nd4", "Hmgcs1", "Ift52", "Fkbpl", "Fut10", "Hapln1", "Mal2", "Mal", "Rtkn2", "Gabra1", "C1qb", "Qdpr", "Glrb", "Mt-cytb", "Pfdn5", "Rps14", "Prps1", "Mien1", "Atp6v1d", "Ift22", "Snx2", "Gpr22", "Crispld1", "Zmym2", "Pink1", "Mff", "Arhgap12", "Ccng1", "Tmsb4x", "Auts2", "Flrt1", "Sulf1", "Vwf")

#heatmaps WT vs 3xTg Ctrl
pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% metab, c(13:16, 1:3)], scale = "row", clustering_distance_rows = "correlation", show_rownames = T, cluster_cols = F, gaps_col = 4, treeheight_col = 10, cellwidth = 10, cellheight = 9, main = "Energy Metabolism", filename = "./figures/hm_CTRL_metab.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% synapse, c(13:16, 1:3)], scale = "row", clustering_distance_rows = "correlation", show_rownames = T, cluster_cols = F, gaps_col = 4, treeheight_col = 10, cellwidth = 10, cellheight = 9, main = "Synapse and cell communication", filename = "./figures/hm_CTRL_synapse.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% Neural, c(13:16, 1:3)], scale = "row", clustering_distance_rows = "correlation", show_rownames = T, cluster_cols = F, gaps_col = 4, treeheight_col = 10, cellwidth = 10, cellheight = 9, main = "Neural development", filename = "./figures/hm_CTRL_neuroDev.pdf")

#condensed versions without gene names Controls only
pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% metab, c(13:16, 1:3)], scale = "row", clustering_distance_rows = "correlation", show_rownames = F, cluster_cols = F, gaps_col = 4, treeheight_col = 10, cellwidth = 10, cellheight = 1, main = "Energy Metabolism", filename = "./figures/hm_CTRL_metab_cond.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% synapse, c(13:16, 1:3)], scale = "row", clustering_distance_rows = "correlation", show_rownames = F, cluster_cols = F, gaps_col = 4, treeheight_col = 10, cellwidth = 10, cellheight = 1, main = "Synapse and cell communication", filename = "./figures/hm_CTRL_synapse_cond.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% Neural, c(13:16, 1:3)], scale = "row", clustering_distance_rows = "correlation", show_rownames = F, cluster_cols = F, gaps_col = 4, treeheight_col = 10, cellwidth = 10, cellheight = 1, main = "Neural development", filename = "./figures/hm_CTRL_neuroDev_cond.pdf")


#
#heatmaps WT vs 3xTg Ctrl vs 3xTg K and M
pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% metab, c(13:16, 1:12)], scale = "row", clustering_distance_rows = "correlation", show_rownames = T, cluster_cols = F, gaps_col = c(4,7,12), treeheight_col = 10, cellwidth = 10, cellheight = 9, main = "Energy Metabolism", filename = "./figures/hm_3cond_metab.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% synapse, c(13:16, 1:12)], scale = "row", clustering_distance_rows = "correlation", show_rownames = T, cluster_cols = F, gaps_col = c(4,7,12), treeheight_col = 10, cellwidth = 10, cellheight = 9, main = "Synapse and cell communication", filename = "./figures/hm_3cond_synapse.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% Neural, c(13:16, 1:12)], scale = "row", clustering_distance_rows = "correlation", show_rownames = T, cluster_cols = F, gaps_col = c(4,7,12), treeheight_col = 10, cellwidth = 10, cellheight = 9, main = "Neural development", filename = "./figures/hm_3cond_neuroDev.pdf")

#condensed versions without gene names 4 conditions
pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% metab, c(13:16, 1:12)], scale = "row", clustering_distance_rows = "correlation", show_rownames = F, cluster_cols = F, gaps_col = c(4,7,12), treeheight_col = 10, cellwidth = 10, cellheight = 1, main = "Energy Metabolism", filename = "./figures/hm_3cond_metab_cond.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% synapse, c(13:16, 1:12)], scale = "row", clustering_distance_rows = "correlation", show_rownames = F, cluster_cols = F, gaps_col = c(4,7,12), treeheight_col = 10, cellwidth = 10, cellheight = 1, main = "Synapse and cell communication", filename = "./figures/hm_3cond_synapse_cond.pdf")

pheatmap(normCounts_transcripts[rownames(normCounts_transcripts) %in% Neural, c(13:16, 1:12)], scale = "row", clustering_distance_rows = "correlation", show_rownames = F, cluster_cols = F, gaps_col = c(4,7,12), treeheight_col = 10, cellwidth = 10, cellheight = 1, main = "Neural development", filename = "./figures/hm_3cond_neuroDev_cond.pdf")

```

